server:
  port: 8081
spring:
  profiles:
    active: local
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: Dbpas123*
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
